# Change these first
owner: Cutiei # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: 谷歌Google（本监测的稳定性）
    url: https://www.google.com
  - name: Fire一104.128.189.11
    url: http://104.128.189.11:42176/
  - name: 网站一89.117.94.99
    url: http://89.117.94.99/
 # - name: 性能一（预计删除）173.249.203.183
 #   url: http://173.249.203.183/
  - name: 备份二88.99.163.99:51968
    url: http://88.99.163.99:51968/
  - name: 容器一116.202.49.57:50057
    url: http://116.202.49.57:50057/
  - name: 阿里一106.15.126.131:24211
    url: http://106.15.126.131:24211/
  - name: 对象储存一88.99.163.99:51969
    url: http://88.99.163.99:51969/
 # - name: 邮箱一sslms.h-e.top
 #   url: https://sslms.h-e.top/
 # - name: 对象储存二173.249.203.183:59200
 #   url: http://173.249.203.183:59200/
  - name: 日程同步一（镜像）106.15.126.131:50501
    url: http://106.15.126.131:50501/
  - name: 博客一H-e.top
    url: https://h-e.top/
  - name: 搜索一So.h-e.top
    url: https://so.h-e.top/
  - name: 小说一Www.ycasyy.cn
    url: https://www.ycasyy.cn/
  - name: 防红一Happy.ez6swh.cn
    url: https://happy.ez6swh.cn/
  - name: 梗一Inewsi.cn
    url: https://inewsi.cn/
  - name: 小游戏一Play.h-e.top
    url: https://play.h-e.top/
 # - name: 思维导图一Drawio.h-e.top
 #   url: https://drawio.h-e.top/
  - name: 公益接口一Api.h-e.top
    url: https://api.h-e.top/
 # - name: 我的世界服务器一Mc.2b2t.cyou
 #   url: https://mc.2b2t.cyou/
  - name: 统计一mat.5i.gs
    url: https://mat.5i.gs/
  - name: 联邦宇宙一s.5i.gs
    url: https://s.5i.gs/
  - name: 博客二iviaja.com
    url: https://iviaja.com/
 # - name: RSS抓取一rss.5i.gs
 #   url: https://rss.5i.gs/
  - name: 导航一nav.5i.gs
    url: https://nav.5i.gs
  - name: GIT一git.5i.gs
    url: https://git.5i.gs/
  - name: 网盘一ifs.5i.gs
    url: https://ifs.5i.gs/
  - name: 必应一bing.5i.gs
    url: https://bing.5i.gs/#dialog=%22%22
 # - name: 网盘二box.5i.gs
 #   url: https://box.5i.gs/#user/login
  - name: 笔记一note.5i.gs
    url: https://note.5i.gs/#
  - name: 收藏一wabag.5i.gs
    url: https://wabag.5i.gs/login
  - name: 短链一yourls.5i.gs
    url: https://yourls.5i.gs/
  - name: 图床一img.5i.gs
    url: https://img.5i.gs/
  - name: 图床一（镜像）img.somlife.ru
    url: https://img.somlife.ru/
  - name: 网页部作业一（镜像）chinn.org
    url: http://xn--vhq83ak66hwyoeui.chinn.org
  - name: 网页部作业一（镜像）biring.id	
    url: http://xn--vhq83ak66hwyoeui.biring.id	
  - name: 网页部作业一（镜像）absl.ro	
    url: http://xn--vhq83ak66hwyoeui.absl.ro	
  - name: 网页部作业一（镜像）star.is
    url: http://xn--vhq83ak66hwyoeui.star.is
  - name: 网页部作业一（镜像）corex.se
    url: http://xn--vhq83ak66hwyoeui.corex.se
  - name: 笔记一（镜像）n.i-mind.cl
    url: http://n.i-mind.cl/
  - name: 必应一（镜像）bingo.0x.no
    url: https://bingo.0x.no/
  - name: 导航一（镜像）nav.iiiii.info
    url: https://nav.iiiii.info/
  - name: 导航一（镜像）nav.k.vu
    url: https://nav.k.vu/
  - name: GIT一（镜像）git.hs.vc
    url: https://git.hs.vc/
  - name: StaticJs一（镜像）trac.beclicked.com
    url: https://trac.beclicked.com/
  - name: 搜索一（镜像）searx.ix.tc
    url: https://searx.ix.tc/
 # - name: 协作笔记一cotxt.5i.gs
 #   url: https://cotxt.5i.gs/
 # - name: 协作笔记一（镜像）txt.qc.to
 #   url: https://txt.qc.to/
  - name: 小程序一mini2.396pay.cn
    url: https://mini2.396pay.cn/
 # - name: 画板一dra.5i.gs
 #   url: https://dra.5i.gs/
  - name: 工具一tool.5i.gs
    url: https://tool.5i.gs/
  - name: 剪贴板一cut.5i.gs
    url: https://cut.5i.gs/
  - name: 剪贴板一（镜像）cut.3uu.me
    url: https://cut.3uu.me/
  - name: 专用一（镜像）cadence.jroxg.org
    url: https://cadence.jroxg.org/
  - name: 静态CDN（镜像）106.15.126.131:8443
    url: https://106.15.126.131:8443/
  - name: 小雅一res-ya.5i.gs
    url: https://res-ya.5i.gs/
  - name: 监测一change.5i.gs
    url: https://change.5i.gs/
  - name: Pandora一cgpt.5i.gs
    url: https://cgpt.5i.gs/shared.html
  - name: Pandora一（镜像）chat.htpc.cl
    url: https://chat.htpc.cl/shared.html
  - name: 笔记二（镜像）106.15.126.131:8082
    url: https://106.15.126.131:8082/

    
  
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  ##cname: 
  baseUrl: /Uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  scripts:
    - src: https://trac.5i.gs/host.all-other.5i.gs.js
      async: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
